global: &global
  adapter: postgresql
  username: dev
  min_messages: warning

development:
  database: generic_application_development
  <<: *global

test: &test
  database: generic_application_test_<%= ENV['TEST_ENV_NUMBER'].presence || '1' %>
  <<: *global


